module.exports = {
  mongo:{
    dbName:process.env.MONGO_DB,
    port:process.env.MONGO_PORT,
    host:process.env.MONGO_HOST,
    user:process.env.MONGO_USERNAME,
    password:process.env.MONGO_PASSWORD
  },
  redis:{
    url:process.env.REDISTOGO_URL
  },
  email:{
    server:{
      user:process.env.EMAIL_USER,
      password:process.env.EMAIL_PASSWORD,
      host:process.env.EMAIL_HOST,
      domain:process.env.EMAIL_DOMAIN,
      ssl:true},
    from:process.env.EMAIL_FROM
  },
  hostname:process.env.HOSTNAME
};